Repository opentensor/bittensor-drand, pull requests merged in 2025-04, with the labels that each got.

#21 Add encrypt, decrypt functionality for `bt.timelock`
  Cargo.lock
  Cargo.toml
  bittensor_commit_reveal/__init__.py
  pyproject.toml
  src/drand.rs
  src/lib.rs
  src/python_bindings.rs
  tests/test_all_functions.py
  tests/test_commit_reveal.py
Labels: run-bittensor-sdk-tests

#22 Backmerge main staging 040
  CHANGELOG.MD
  pyproject.toml
  tests/test_commit_reveal.py
Labels: run-bittensor-sdk-tests

#23 0.4.0: Updates changelog
  CHANGELOG.MD
Labels: run-bittensor-sdk-tests

#26 update imports in README.md
  README.md
Labels: documentation

#27 feat: implement ffi , generate C headers
  Cargo.lock
  Cargo.toml
  bindings.h
  cbindgen.toml
  src/drand.rs
  src/ffi.rs
  src/lib.rs
Labels: enhancement

#28 Add permissions
  .github/workflows/check-sdk-tests.yml
Labels: bug

#29 Bumps changelog: 0.5.0
  CHANGELOG.MD
Labels: run-bittensor-sdk-tests

#30 Release/0.5.0
  .github/workflows/check-sdk-tests.yml
  CHANGELOG.MD
  Cargo.lock
  Cargo.toml
  README.md
  bindings.h
  bittensor_drand/__init__.py
  cbindgen.toml
  pyproject.toml
  src/drand.rs
  src/ffi.rs
  src/lib.rs
  src/python_bindings.rs
  tests/test_all_functions.py
  tests/test_commit_reveal.py
Labels: run-bittensor-sdk-tests
